import {useState,useEffect} from 'react'
import {api,fetchBootstrap} from './api'
import {LayoutGrid,Users,Rss,Inbox,Clock,MessagesSquare,Activity,Settings,Search,Bell,Check,X,Pencil,Flame,Sparkles,ArrowUpRight,CornerDownRight,Github,Copy,ShieldCheck} from 'lucide-react'

type Kind='DM'|'Comment'|'Follow-up'
const leads=[
{id:1,via:2,name:'Daniel Okafor',role:'Staff Engineer',co:'Tessellate',score:94,status:'Awaiting approval',act:'DM',last:'2h ago',tags:['Python','pytest','CI infra','Flaky tests'],why:'Wrote that a pytest integration suite fails about 1 in 20 runs on GitHub Actions and he cannot reproduce it locally. Maintains the team’s CI tooling.',ev:['Posted about intermittent failures 2 days ago','Maintains pytest plugins at Tessellate','Active in pytest-dev discussions']},
{id:2,via:1,name:'Sarah Chen',role:'Software Engineer',co:'Loomfield',score:91,status:'Awaiting approval',act:'Comment',last:'5h ago',tags:['pytest','GitHub Actions','Flaky tests'],why:'Asked publicly whether anyone else sees flaky pytest integration tests in GitHub Actions. Direct match for the problem Flaky-Repro solves.',ev:['Open question about flaky pytest in CI','Replies to others within hours','Python-only stack']},
{id:3,via:3,name:'Marcus Lindqvist',role:'Test Infrastructure Lead',co:'Northbeam',score:86,status:'New',act:'DM',last:'1d ago',tags:['E2E','CI infra','Python'],why:'Gave a talk on quarantining flaky E2E tests. Quarantine is a workaround; he may want root-cause tooling.',ev:['Conference talk on flaky E2E tests','Owns the CI platform team','Uses pytest-xdist']},
{id:4,name:'Priya Raghavan',role:'Maintainer, pytest-retry-extras',co:'Open source',score:82,status:'Contacted',act:'Follow-up',last:'6d ago',tags:['pytest','OSS maintainer'],why:'Maintains a retry plugin, so she sees flaky tests daily. Contacted 6 days ago, no reply yet.',ev:['Maintains a pytest plugin','Issue tracker has 14 flaky-test reports']},
{id:5,name:'Tomás Herrera',role:'Backend Engineer',co:'Quayside',score:71,status:'Replied',act:'Reply',last:'3h ago',tags:['Python','CI'],why:'Replied asking how Flaky-Repro differs from rerunning with pytest-rerunfailures.',ev:['Asked a specific product question']},
{id:6,name:'Alex Whitford',role:'Senior Python Engineer',co:'Brightlane',score:34,status:'New',act:'Ignore',last:'4d ago',tags:['Python'],why:'Not enough evidence. Job title matches, but no posts about tests or CI. Ignore.',ev:['No problem signals found']}]
const posts=[
{id:1,url:'github.com/loomfield/ci/discussions/412',who:'Sarah Chen',role:'Software Engineer · Loomfield',score:94,when:'2 days ago',txt:'Anyone else dealing with flaky pytest integration tests in GitHub Actions? Passes locally every time, fails roughly one run in twenty on CI.',why:'Directly matches the problem Flaky-Repro investigates, and the question is still open.',sig:['pytest','CI','flaky tests','active thread'],act:'Comment',draft:'I’ve run into this pattern too. Comparing the conditions of a passing run against a failing one (ordering, env, timing) usually narrows it faster than rerunning. I’m building an open-source pytest tool around that idea. Happy to try it on one of your failing tests if useful.'},
{id:2,url:'mastodon.social/@dokafor/113904',who:'Daniel Okafor',role:'Staff Engineer · Tessellate',score:91,when:'3 days ago',txt:'Spent the day bisecting a test that only fails when run after test_billing. Shared state again. Why is this still so manual?',why:'Order-dependent failure, a core Flaky-Repro scenario. He also asked why it is still manual.',sig:['test ordering','shared state','pytest'],act:'Comment',draft:'Order-dependent failures are brutal to bisect by hand. Does it also change when you shuffle with a fixed seed? That tells you whether it is the ordering or the shared fixture.'},
{id:3,url:'northbeam.dev/blog/quarantine-debt',who:'Marcus Lindqvist',role:'Test Infrastructure Lead · Northbeam',score:77,when:'5 days ago',txt:'We quarantined 40 flaky tests this quarter. Nobody wants to own fixing them.',why:'Real pain, but no ask. A comment may read as a pitch, so the agent recommends a DM later.',sig:['quarantine','E2E'],act:'Ignore',draft:''}]
const queue:{id:number;kind:Kind;who:string;co:string;ctx:string;why:string;text:string}[]=[
{id:1,kind:'DM',who:'Daniel Okafor',co:'Tessellate',ctx:'',why:'Uses pytest and posted about order-dependent CI failures this week.',text:'Hey Daniel, saw your post about the test that only fails after test_billing. I’m building Flaky-Repro, an open-source pytest CLI that reruns a failing test under different orderings and environments and reports what changed. It might save you the manual bisecting. Want me to point it at that test?'},
{id:2,kind:'Comment',who:'Sarah Chen',co:'Loomfield',ctx:'“Anyone else dealing with flaky pytest integration tests in GitHub Actions?”',why:'Open question about the exact problem space, 2 days old.',text:posts[0].draft},
{id:3,kind:'Follow-up',who:'Priya Raghavan',co:'pytest-retry-extras',ctx:'Last contacted 6 days ago, no reply',why:'Maintains a retry plugin; one gentle nudge is reasonable.',text:'Hey Priya, following up on my note last week. No pressure. If retries ever hide a failure you want to understand, Flaky-Repro might be a useful complement. Happy to share a quick example.'},
{id:4,kind:'DM',who:'Marcus Lindqvist',co:'Northbeam',ctx:'',why:'Talk on quarantining flaky E2E tests; likely wants root causes.',text:'Hi Marcus, your talk on quarantining flaky E2E tests resonated. I’m working on an open-source pytest tool that tries to explain why a test flakes instead of hiding it. Would you be open to trying it on one quarantined test?'},
{id:5,kind:'Comment',who:'Daniel Okafor',co:'Tessellate',ctx:'“Why is this still so manual?”',why:'Order-dependent failure thread, still active.',text:posts[1].draft}]
const convos=[
{id:1,who:'Tomás Herrera',intent:'High interest',status:'Interested',when:'3h ago',last:'How is this different from pytest-rerunfailures?',read:'High interest. Asked how Flaky-Repro works.',next:'Explain the investigation workflow and offer to test it on one of his flaky tests.',msgs:[['me','Hey Tomás, saw your note about CI flakiness. I’m building Flaky-Repro, an open-source pytest tool for investigating them.'],['them','Interesting. How is this different from pytest-rerunfailures?']],draft:'rerunfailures hides a flake by retrying. Flaky-Repro reruns the test under varied conditions (order, seed, env) and tells you which one flips the result. If you have a test that flakes, send me the name and I’ll show you the output.'},
{id:2,who:'Mei Tanaka',intent:'Neutral',status:'Waiting',when:'1d ago',last:'Thanks, I’ll take a look this weekend.',read:'Polite, no commitment yet.',next:'Wait until Monday, then send one follow-up.',msgs:[['me','Here is the repo link if you want to try it.'],['them','Thanks, I’ll take a look this weekend.']],draft:''},
{id:3,who:'Jonas Weber',intent:'Low interest',status:'Not interested',when:'4d ago',last:'We use a commercial tool already.',read:'Not a fit right now.',next:'Do not follow up.',msgs:[['them','We use a commercial tool already.']],draft:''}]
const feed=[['You approved DM to Tomás Herrera','2h ago','you'],['Agent classified reply from Tomás as HIGH INTENT','3h ago','agent'],['Agent generated comment draft for Sarah Chen','5h ago','agent'],['Agent scored Daniel Okafor 94/100','6h ago','agent'],['Agent discovered Daniel Okafor from a public post','6h ago','agent'],['Agent decided to ignore Alex Whitford: not enough evidence','1d ago','agent'],['You rejected a comment draft (too salesy)','1d ago','you'],['DM sent to Priya Raghavan','6d ago','sent']]
const nav=[['Overview',LayoutGrid],['Leads',Users],['Post Opportunities',Rss],['Approval Queue',Inbox],['Follow-ups',Clock],['Conversations',MessagesSquare],['Activity',Activity],['Settings',Settings]] as const

const hue=(s:string)=>[...s].reduce((a,c)=>a+c.charCodeAt(0),0)*37%360
const Av=({n,s=32}:{n:string;s?:number})=><div className="shrink-0 grid place-items-center rounded-full font-medium text-[11px]" style={{width:s,height:s,background:`hsl(${hue(n)} 35% 22%)`,color:`hsl(${hue(n)} 70% 78%)`}}>{n.split(' ').map(w=>w[0]).slice(0,2).join('')}</div>
const Score=({v}:{v:number})=>{const c=v>=80?'text-ok bg-ok/10':v>=50?'text-warn bg-warn/10':'text-dim bg-raise';return <span className={`font-mono text-[12px] px-1.5 py-0.5 rounded ${c}`}>{v}</span>}
const Pill=({children,t='n'}:{children:any;t?:string})=><span className={`text-[11.5px] px-2 py-0.5 rounded-full border ${t==='a'?'border-accent/40 text-accent bg-accent/10':t==='ok'?'border-ok/30 text-ok':'border-line text-dim'}`}>{children}</span>
const Btn=({children,onClick,v='g'}:{children:any;onClick?:()=>void;v?:'g'|'p'|'x'})=><button onClick={onClick} className={`inline-flex items-center gap-1.5 h-8 px-3 rounded-md text-[13px] font-medium transition ${v==='p'?'bg-accent text-[#0b0c10] hover:brightness-110':v==='x'?'text-dim hover:text-bad hover:bg-bad/10':'border border-line text-ink hover:bg-raise'}`}>{children}</button>
const Head=({t,s,r}:{t:string;s:string;r?:any})=><div className="flex items-end justify-between mb-5"><div><h1 className="text-[22px] font-semibold tracking-tight">{t}</h1><p className="text-dim mt-0.5">{s}</p></div>{r}</div>
const Empty=({t,s}:{t:string;s:string})=><div className="py-20 text-center"><div className="mx-auto mb-3 size-10 rounded-full bg-raise grid place-items-center"><Sparkles size={16} className="text-dim"/></div><div className="font-medium">{t}</div><p className="text-dim mt-1">{s}</p></div>

export const stats={new_leads:12,new_leads_24h:4,post_opportunities:18,followups:2,overdue:1}
export const followups:[string,string,string,string,number][]=[['Priya Raghavan','6 days ago','Overdue','Hey Priya, following up on my note last week. No pressure. If retries ever hide a failure you want to understand, Flaky-Repro might be a useful complement.',1001],['Mei Tanaka','2 days ago','Due Monday','Hope the weekend test run went well. Happy to look at any output that looks odd.',1002]]
export const agentInfo={running:true,last:'8 min ago',next:'in 22 min',people:42,posts:73,opps:12,drafts:7,recent:[['Researching 2 new authors','now'],['Generated comment draft for Sarah Chen','5h'],['Updated Daniel Okafor score to 94','6h'],['Found post about flaky CI in pytest-dev','6h']] as string[][]}
// Replaces the built-in mock data with backend data (arrays are mutated in place so the rest of the UI is unchanged).
export const loadData=(d:any)=>{const set=(a:any[],b:any[])=>a.splice(0,a.length,...b);set(leads,d.leads);set(posts,d.posts);set(queue,d.queue);set(convos,d.convos);set(feed,d.feed);set(followups,d.followups);Object.assign(stats,d.stats);Object.assign(agentInfo,d.agent)}
const Dot=({on}:{on:boolean})=><span className={`size-1.5 rounded-full ${on?'live bg-ok':'bg-dim'}`}/>
const lab=(v:number)=>v>=80?'High relevance':v>=50?'Medium relevance':'Low confidence'
const L=(n:string)=>leads.find(l=>l.name===n)
const sc=(x:{kind:string;who:string})=>(x.kind==='Comment'?pOf(x)?.score:lOf(x)?.score)??0
const inTab=(x:{kind:string},t:string)=>t==='All'||x.kind+'s'===t
const Why=({t,score,ev,note,sig}:{t:string;score:number;ev:string[];note?:string;sig?:string[]})=>{const I=score<50?X:Check;return <div><div className="flex items-center justify-between mb-2"><h3 className="font-medium">{t}</h3><span className="flex items-center gap-2"><Score v={score}/><span className="text-dim text-[12px]">/ 100 · {lab(score)}</span></span></div><ul className="space-y-1.5">{ev.map(e=><li key={e} className="flex gap-2"><I size={14} className={`mt-1 shrink-0 ${score<50?'text-dim':'text-ok'}`}/>{e}</li>)}</ul>{sig&&<div className="flex gap-1.5 mt-3 flex-wrap">{sig.map(x=><Pill key={x}>{x}</Pill>)}</div>}{note&&<p className="text-dim mt-2.5 leading-relaxed">{note}</p>}</div>}
// Opens the public post in a new tab. Navigation only. Falls back to the scheme-less `url` if post_url is missing or not http(s).
const postHref=(p:any):string=>/^https?:\/\//i.test(p.post_url||'')?p.post_url:'https://'+p.url
// GitHub opportunities. Everything below is read-only display + local clipboard + a plain link. Nudge never calls GitHub from the UI.
const isGh=(x:any)=>x?.source==='github:issue'
const ghHref=(p:any):string=>{const u=p?.github?.issue_url||p?.issue_url||p?.post_url||'';return /^https:\/\/github\.com\//i.test(u)?u:''}   // only real github.com URLs are linkable
const copyText=async(t:string):Promise<boolean>=>{try{await navigator.clipboard.writeText(t);return true}catch{try{const a=document.createElement('textarea');a.value=t;a.style.cssText='position:fixed;opacity:0';document.body.appendChild(a);a.select();const ok=document.execCommand('copy');a.remove();return ok}catch{return false}}}
const GH_NOTE='Approving only marks this draft approved inside Nudge. Nothing is posted to GitHub: open the issue and paste the comment yourself.'
const dst=(s:string|null)=>s?({AWAITING_APPROVAL:'Awaiting approval',APPROVED:'Approved',REJECTED:'Rejected',NOT_RELEVANT:'Not relevant'} as any)[s]??s:''
const pOf=(x:any)=>x.post_id?posts.find(p=>p.id===x.post_id):posts.find(p=>p.who===x.who)   // queue item -> its post (by id when the backend gives one)
const lOf=(x:any)=>x.lead_id?leads.find(l=>l.id===x.lead_id):L(x.who)
const Src=({p}:{p:any})=>{const g=isGh(p),h=g?ghHref(p):postHref(p);return <div className="rounded-md border border-line bg-bg p-3"><div className="flex items-center justify-between text-[12px] text-dim"><span className="flex items-center gap-1.5"><Clock size={12}/>{g?'Updated':'Posted'} {p.when}</span>{h&&<a href={h} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-accent hover:underline">{g?'Open Issue':'Open Post'}<ArrowUpRight size={12}/></a>}</div>{g&&p.github?<><div className="mt-1.5 font-medium">{p.github.repository} #{p.github.number}: {p.github.title}</div>{p.github.excerpt&&<p className="mt-1 text-dim leading-relaxed line-clamp-3">{p.github.excerpt}</p>}</>:<p className="mt-1.5 leading-relaxed">“{p.txt}”</p>}</div>}
const AgentPanel=({onRun,running,live}:{onRun:()=>void;running:boolean;live:boolean})=><div className="slide absolute bottom-full mb-2 left-0 w-[300px] max-h-[calc(100vh-240px)] overflow-y-auto rounded-lg border border-line bg-panel shadow-2xl p-4 z-30 text-[12.5px]"><div className="flex items-center gap-2 font-medium"><Dot on={live}/>{live?'Agent running':'Agent idle'}</div><div className="grid grid-cols-2 gap-px bg-line rounded-md overflow-hidden border border-line mt-3">{[['People analyzed',agentInfo.people],['Posts analyzed',agentInfo.posts],['Opportunities found',agentInfo.opps],['Drafts generated',agentInfo.drafts]].map(([a,b])=><div key={a as string} className="bg-panel p-2.5"><div className="text-[18px] font-semibold">{b}</div><div className="text-dim text-[11.5px]">{a}</div></div>)}</div><div className="text-dim mt-3 mb-1.5">{`Last scan ${agentInfo.last} · ${agentInfo.next}`}</div><div className="space-y-2 border-l border-line pl-3">{agentInfo.recent.map(([t,w],i)=><div key={t} className="flex justify-between gap-2"><span className={i?'text-dim':''}>{t}</span><span className="text-dim shrink-0">{w}</span></div>)}</div><button onClick={onRun} disabled={running} className="mt-3 w-full h-8 rounded-md border border-line hover:bg-raise text-[13px] disabled:opacity-50 transition">{running?'Scanning…':'Run scan now'}</button></div>
export default function App(){
const [,tick]=useState(0),[running,setRunning]=useState(false),[hid,setHid]=useState<Record<string,string>>({}),[agent,setAgent]=useState(false),[editing,setEditing]=useState<number|null>(null),[page,setPage]=useState('Overview'),[open,setOpen]=useState<number|null>(null),[q,setQ]=useState(queue),[tab,setTab]=useState('All'),[sel,setSel]=useState(1),[toast,setToast]=useState(''),[filter,setFilter]=useState('All'),[cv,setCv]=useState(0),[edits,setEdits]=useState<Record<number,string>>({}),[src,setSrc]=useState('All')
const live=running||agentInfo.running
const vis=q.filter(x=>inTab(x,tab))
const done=(id:number,verb:string)=>{const it=q.find(x=>x.id===id)!;const i=vis.findIndex(x=>x.id===id);const nx=vis[i+1]??vis[i-1];setQ(q.filter(x=>x.id!==id));api(`/drafts/${id}/${verb==='Approved'?'approve':verb==='Rejected'?'reject':'not-relevant'}`,'POST',verb==='Approved'&&edits[id]!==undefined?{content:edits[id]}:undefined);setEditing(null);if(nx)setSel(nx.id);
if(isGh(it)){const po:any=posts.find(p=>p.id===(it as any).post_id);if(po){po.status=verb==='Approved'?'Approved':verb==='Rejected'?'Rejected':'Not relevant';po.draft_status=verb==='Approved'?'APPROVED':verb==='Rejected'?'REJECTED':'NOT_RELEVANT';if(verb==='Approved'&&edits[id]!==undefined)po.draft=edits[id];if(verb!=='Approved'&&verb!=='Rejected')setHid(h=>({...h,['p'+po.id]:verb}))}}
setToast(`${verb}: ${it.kind} to ${it.who}${verb==='Approved'?(isGh(it)?' · saved in Nudge only, nothing posted to GitHub':' · demo mode, nothing sent'):''}`);setTimeout(()=>setToast(''),isGh(it)?4200:2400)}
const copy=async(t:string)=>{const ok=await copyText(t);setToast(ok?'Draft copied to clipboard':'Copy failed: select the text and copy it manually');setTimeout(()=>setToast(''),2400)}
const hide=(k:string,v:string,n:string)=>{setHid({...hid,[k]:v});api((k[0]==='l'?'/leads/':'/posts/')+k.slice(1)+'/dismiss','POST',{reason:v==='Ignored'?'IGNORED':'NOT_RELEVANT'});setToast(`${v}: ${n}`);setTimeout(()=>setToast(''),2400)}
const refresh=async()=>{const d=await fetchBootstrap();if(d){loadData(d);setQ([...queue]);tick(n=>n+1)}}
const runScan=async()=>{setRunning(true);await api('/agent/run','POST');for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,700));const s=await api('/agent/status');if(s&&!s.running)break}await refresh();setRunning(false)}
const fu=(id:number,a:string,n:string)=>{api(`/drafts/${id}/${a}`,'POST');followups.splice(followups.findIndex(f=>f[4]===id),1);setQ(q.filter(x=>x.id!==id));setToast(`${a==='approve'?'Approved':'Rejected'}: follow-up to ${n}${a==='approve'?' · demo mode, nothing sent':''}`);setTimeout(()=>setToast(''),2400)}
useEffect(()=>{const h=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(page!=='Approval Queue'||t.tagName==='TEXTAREA'||t.tagName==='INPUT'||e.metaKey||e.ctrlKey)return;const c=vis.find(x=>x.id===sel)??vis[0];if(!c)return;const i=vis.indexOf(c),k=e.key.toLowerCase();if(k==='j'&&vis[i+1])setSel(vis[i+1].id);else if(k==='k'&&vis[i-1])setSel(vis[i-1].id);else if(k==='a')done(c.id,'Approved');else if(k==='r')done(c.id,'Rejected');else if(k==='e'){e.preventDefault();setEditing(c.id)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)})
const lead=leads.find(l=>l.id===open)
const Row=({l}:{l:typeof leads[0]})=><button onClick={()=>setOpen(l.id)} className="w-full text-left flex items-start gap-3 px-4 py-3.5 border-b border-line hover:bg-raise/60 transition"><Av n={l.name}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-medium">{l.name}</span><span className="text-dim truncate">{[l.role,l.co].filter(Boolean).join(' · ')}</span>{isGh(l)&&<Pill><span className="inline-flex items-center gap-1"><Github size={11}/>GitHub</span></Pill>}</div><p className="text-dim mt-1 line-clamp-1">{l.why}</p>{l.via&&posts.find(p=>p.id===l.via)&&<div className="text-[12px] text-dim mt-1 flex items-center gap-1"><Rss size={11}/>Found via {isGh(l)?'GitHub issue':'post'} · {posts.find(p=>p.id===l.via)!.when}</div>}<div className="flex gap-1.5 mt-2 flex-wrap">{l.tags.map(t=><Pill key={t}>{t}</Pill>)}</div></div><div className="hidden sm:flex flex-col items-end gap-1.5 text-[12px]"><Score v={l.score}/><span className="text-dim">{l.last}</span><Pill t={l.act==='Ignore'?'n':'a'}>{l.act}</Pill></div></button>
const Draft=({d,id}:{d:typeof queue[0];id:number})=>{const ed=editing===id;const txt=edits[id]??d.text;return <div className="rounded-lg border border-line bg-panel p-4"><div className="flex justify-between text-dim text-[12px] mb-1.5"><span>Draft {isGh(d)?'GitHub comment':d.kind.toLowerCase()}</span><span>{txt.length} chars{edits[id]!==undefined&&' · edited'}</span></div><textarea ref={el=>{if(ed&&el&&document.activeElement!==el)el.focus()}} readOnly={!ed} value={txt} onChange={e=>setEdits({...edits,[id]:e.target.value})} rows={5} className={`w-full resize-none bg-bg border rounded-md p-3 leading-relaxed ${ed?'border-accent/60':'border-line'}`}/><div className="flex flex-wrap justify-between gap-2 mt-3"><div className="flex gap-1"><Btn v="x" onClick={()=>done(id,'Rejected')}><X size={14}/>Reject</Btn><Btn v="x" onClick={()=>done(id,'Marked not relevant')}>Not relevant</Btn></div><div className="flex flex-wrap gap-2">{isGh(d)&&<><Btn onClick={()=>copy(txt)}><Copy size={13}/>Copy draft</Btn>{ghHref(d)&&<a href={ghHref(d)} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 h-8 px-3 rounded-md text-[13px] font-medium border border-line text-ink hover:bg-raise transition"><Github size={13}/>Open Issue<ArrowUpRight size={12}/></a>}</>}<Btn onClick={()=>setEditing(ed?null:id)}><Pencil size={13}/>{ed?'Done editing':'Edit'}</Btn><Btn v="p" onClick={()=>done(id,'Approved')}><Check size={14}/>{isGh(d)?'Approve in Nudge':d.kind==='Comment'?'Approve & comment':'Approve & send'}</Btn></div></div>{isGh(d)&&<p className="text-dim text-[12px] mt-3 flex gap-1.5"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-ok"/>{GH_NOTE}</p>}</div>}
const body=()=>{
if(page==='Overview')return <>
<Head t="Good morning, Mrigank" s="Your agent found new opportunities while you were away."/>
<div className="grid grid-cols-2 xl:grid-cols-4 gap-px bg-line rounded-lg overflow-hidden border border-line mb-8">{[['New leads',stats.new_leads,`+${stats.new_leads_24h} in the last 24h`],['Post opportunities',stats.post_opportunities,'from the last 7 days'],['Awaiting approval',q.length,'nothing sends without you'],['Follow-ups',followups.length,`${stats.overdue} overdue`]].map(([a,b,c])=><div key={a as string} className="bg-panel p-4"><div className="text-dim">{a}</div><div className="text-[28px] font-semibold tracking-tight mt-1">{b}</div><div className="text-dim text-[12px]">{c}</div></div>)}</div>
<h2 className="font-medium mb-3 flex items-center gap-2"><Flame size={15} className="text-warn"/>Needs your attention</h2>
<div className="rounded-lg border border-warn/25 bg-warn/[0.04] p-4 mb-8 flex gap-4 items-start"><Av n="Sarah Chen" s={38}/><div className="flex-1 min-w-0"><div className="flex gap-2 items-center"><span className="font-medium">Sarah Chen</span><span className="text-dim">Software Engineer · Loomfield</span><Pill t="a">High priority</Pill></div><p className="mt-1.5"><span className="text-dim">Reason:</span> Asked publicly about flaky pytest failures in GitHub Actions, 2 days ago and still unanswered.</p><p className="text-dim mt-0.5">Recommended: comment</p></div><div className="flex gap-2"><Btn onClick={()=>setPage('Post Opportunities')}>View</Btn><Btn v="p" onClick={()=>setPage('Approval Queue')}>Review draft</Btn></div></div>
<h2 className="font-medium mb-3">Recent opportunities</h2>
<div className="rounded-lg border border-line bg-panel overflow-hidden">{leads.filter(l=>!hid['l'+l.id]).slice(0,5).map(l=><Row key={l.id} l={l}/>)}</div></>
if(page==='Leads'){const f=['All','New','High intent','Awaiting approval','Contacted','Replied','Interested','Not interested'];const list=leads.filter(l=>!hid['l'+l.id]).filter(l=>filter==='All'||(filter==='High intent'?l.score>=85:l.status.toLowerCase()===filter.toLowerCase()));return <>
<Head t="Leads" s="People the agent thinks are worth talking to."/>
<div className="flex gap-1.5 mb-4 flex-wrap">{f.map(x=><button key={x} onClick={()=>setFilter(x)} className={`h-7 px-2.5 rounded-md text-[12.5px] transition ${filter===x?'bg-raise text-ink border border-line':'text-dim hover:text-ink'}`}>{x}</button>)}</div>
<div className="rounded-lg border border-line bg-panel overflow-hidden">{list.length?list.map(l=><Row key={l.id} l={l}/>):<Empty t="No leads here yet" s="The agent adds people as it finds real problem signals."/>}</div></>}
if(page==='Post Opportunities'){const ps=posts.filter(p=>!hid['p'+p.id]).filter(p=>src==='All'||(src==='GitHub'?isGh(p):!isGh(p)));return <><Head t="Post opportunities" s="Public posts from the last 7 days worth a reply."/>
{posts.some(isGh)&&<div className="flex gap-1.5 mb-4">{['All','LinkedIn','GitHub'].map(x=><button key={x} onClick={()=>setSrc(x)} className={`h-7 px-2.5 rounded-md text-[12.5px] transition ${src===x?'bg-raise text-ink border border-line':'text-dim hover:text-ink'}`}>{x}</button>)}</div>}
<div className="space-y-4 max-w-3xl">{ps.length?ps.map(p=>{const g=isGh(p),ld=g?leads.find(l=>l.id===(p as any).lead_id):L(p.who);return <div key={p.id} className="rounded-lg border border-line bg-panel">
<div className="flex items-center gap-3 p-5 pb-0"><Av n={p.who}/><div className="flex-1 min-w-0"><div className="font-medium">{g?'@'+p.who:p.who}</div><div className="text-dim text-[12px]">{g?<span className="inline-flex items-center gap-1"><Github size={12}/>GitHub · {(p as any).github?.repository} #{(p as any).github?.number}</span>:p.role}</div></div><div className="text-right"><Score v={p.score}/><div className="text-dim text-[11.5px] mt-0.5">{lab(p.score)}</div></div></div>
<div className="px-5 mt-3 flex items-center gap-2 flex-wrap text-[12px]"><Pill><span className="inline-flex items-center gap-1"><Clock size={11}/>{g?'Updated':'Posted'} {p.when}</span></Pill><Pill t={p.act==='Ignore'?'n':'a'}>{g?'Classified':'Recommended'}: {g?p.act.toUpperCase():p.act}</Pill>{g&&<Pill t={(p as any).status==='Approved'?'ok':'n'}>{(p as any).status}</Pill>}{(g?ghHref(p):postHref(p))&&<a href={g?ghHref(p):postHref(p)} target="_blank" rel="noopener noreferrer" className="ml-auto flex items-center gap-1 text-accent hover:underline">{g?'Open Issue':'Open Post'}<ArrowUpRight size={12}/></a>}</div>
{g&&(p as any).github?<div className="mx-5 mt-3 border-l-2 border-line pl-3"><div className="text-[15px] font-medium leading-snug">{(p as any).github.title}</div>{(p as any).github.excerpt&&<p className="mt-1 text-dim leading-relaxed line-clamp-3">{(p as any).github.excerpt}</p>}{[...(p as any).github.frameworks,...(p as any).github.ci].length>0&&<div className="flex gap-1.5 mt-2 flex-wrap items-center text-[12px] text-dim">Stack:{[...(p as any).github.frameworks,...(p as any).github.ci].map((x:string)=><Pill key={x} t="a">{x}</Pill>)}</div>}</div>:<p className="mx-5 mt-3 text-[15px] leading-relaxed border-l-2 border-line pl-3">{p.txt}</p>}
<div className="p-5 space-y-4"><Why t={g?'Why this issue':'Why this post'} score={p.score} ev={p.sig.map(x=>'Signal: '+x)} note={p.why}/>
{g?(p.draft?<div className="rounded-md bg-bg border border-line p-3"><div className="flex items-center justify-between gap-2 text-dim text-[12px] mb-1"><span>Suggested comment draft · {dst((p as any).draft_status)}</span><button onClick={()=>copy(p.draft)} className="inline-flex items-center gap-1 text-accent hover:underline"><Copy size={12}/>Copy draft</button></div><p className="leading-relaxed">{p.draft}</p><p className="text-dim text-[12px] mt-2.5 flex gap-1.5"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-ok"/>{GH_NOTE}</p></div>:<div className="rounded-md bg-raise p-3 text-dim">Classified IGNORE: not enough evidence of this pain to comment. No draft was generated.</div>)
:p.draft?<div className="rounded-md bg-bg border border-line p-3"><div className="text-dim text-[12px] mb-1">Suggested {p.act.toLowerCase()}</div><p className="leading-relaxed">{p.draft}</p></div>:<div className="rounded-md bg-raise p-3 text-dim">Low confidence. Not enough evidence to comment without sounding like a pitch. Ignore for now.</div>}</div>
<div className="flex items-center justify-between gap-2 border-t border-line px-5 py-3">{ld?<button onClick={()=>setOpen(ld.id)} className="text-accent hover:underline flex items-center gap-1 text-[12px]"><Users size={12}/>Lead: {ld.name} · {ld.score}/100</button>:<span/>}<div className="flex gap-1.5"><Btn v="x" onClick={()=>hide('p'+p.id,'Ignored',p.who+'’s post')}>Ignore</Btn><Btn v="x" onClick={()=>hide('p'+p.id,'Marked not relevant',p.who+'’s post')}>Not relevant</Btn>{p.draft&&(!g||(p as any).draft_status==='AWAITING_APPROVAL')&&<Btn v="p" onClick={()=>{setSel(queue.find(x=>g?(x as any).post_id===p.id:x.kind===p.act&&x.who===p.who)?.id??1);setTab('All');setPage('Approval Queue')}}>Review in queue</Btn>}</div></div></div>}):<Empty t="No post opportunities left" s="New posts appear after the next scan."/>}</div></>}
if(page==='Approval Queue'){const cur=vis.find(x=>x.id===sel)??vis[0];const l=cur&&lOf(cur);const cm=cur?.kind==='Comment';const pst=cur&&(cm?pOf(cur):l?.via?posts.find(p=>p.id===l.via):undefined);return <><Head t="Approval queue" s={`${q.length} drafts waiting. Nothing is sent until you approve it.`} r={<div className="hidden md:flex gap-3 text-dim text-[12px]">{[['J/K','navigate'],['A','approve'],['E','edit'],['R','reject']].map(([k,v])=><span key={k}><kbd className="font-mono border border-line rounded px-1 mr-1">{k}</kbd>{v}</span>)}</div>}/>
<div className="flex gap-1 mb-4 border-b border-line">{['All','DMs','Comments','Follow-ups'].map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 pb-2.5 -mb-px border-b-2 transition ${tab===t?'border-accent text-ink':'border-transparent text-dim hover:text-ink'}`}>{t}<span className="font-mono text-[11px] text-dim ml-1.5">{q.filter(x=>inTab(x,t)).length}</span></button>)}</div>
{!cur?<Empty t="Queue cleared" s="New drafts appear here after the next scan."/>:<div className="grid lg:grid-cols-[320px_1fr] gap-4"><div className="rounded-lg border border-line bg-panel overflow-hidden self-start">{vis.map(x=><button key={x.id} onClick={()=>setSel(x.id)} className={`w-full text-left p-3 border-b border-line flex gap-3 transition ${cur.id===x.id?'bg-raise':'hover:bg-raise/50'}`}><Av n={x.who} s={28}/><div className="min-w-0 flex-1"><div className="flex gap-2 items-center"><span className="font-medium truncate">{x.who}</span><span className="ml-auto"><Score v={sc(x)}/></span></div><div className="flex gap-2 items-start mt-1"><Pill t="a">{x.kind}</Pill>{isGh(x)&&<Pill><span className="inline-flex items-center gap-1"><Github size={11}/>GitHub</span></Pill>}<p className="text-dim line-clamp-2 text-[12.5px]">{x.why}</p></div></div></button>)}</div>
<div className="space-y-5 min-w-0"><div className="flex items-center gap-3"><Av n={cur.who} s={38}/><div className="flex-1"><div className="font-medium text-[16px]">{isGh(cur)?'@'+cur.who:cur.who}</div><div className="text-dim">{isGh(cur)?<span className="inline-flex items-center gap-1"><Github size={12}/>GitHub · {cur.co}</span>:l?`${l.role} · ${cur.co}`:cur.co}</div></div><Pill t="a">Recommended: {cur.kind}</Pill></div>
{pst&&<div><div className="text-dim text-[12px] mb-1.5">{cm?'Replying to':'Found via'}</div><Src p={pst}/></div>}
<Why t={isGh(cur)?'Why this issue':cm?'Why this post':'Why this lead'} score={sc(cur)} ev={cm&&pst?pst.sig.map(x=>'Signal: '+x):l?l.ev:[]} sig={!cm&&l?l.tags:undefined}/>
<div><h3 className="font-medium mb-1">Why this action</h3><p className="text-dim leading-relaxed">{cur.why}{cur.ctx&&!pst?` ${cur.ctx}.`:''}</p></div>
<Draft d={cur} id={cur.id}/></div></div>}</>}
if(page==='Follow-ups')return <><Head t="Follow-ups" s="People who haven’t replied yet."/><div className="max-w-3xl space-y-3">{followups.map(([n,w,u,t,fid])=><div key={n} className="rounded-lg border border-line bg-panel p-4"><div className="flex items-center gap-3"><Av n={n}/><div className="flex-1"><div className="font-medium">{n}</div><div className="text-dim text-[12px]">Last contacted {w}. No response.</div></div><Pill t={u==='Overdue'?'a':'n'}>{u}</Pill></div><p className="mt-3 p-3 bg-bg border border-line rounded-md leading-relaxed">{t}</p><div className="flex justify-end gap-2 mt-3"><Btn v="x" onClick={()=>fu(fid,'reject',n)}>Reject</Btn><Btn onClick={()=>setPage('Approval Queue')}><Pencil size={13}/>Edit in queue</Btn><Btn v="p" onClick={()=>fu(fid,'approve',n)}><Check size={14}/>Approve & send</Btn></div></div>)}</div></>
if(page==='Conversations'){const c=convos[cv];return <><Head t="Conversations" s="Replies, classified by intent."/><div className="grid lg:grid-cols-[320px_1fr] gap-4"><div className="rounded-lg border border-line bg-panel overflow-hidden self-start">{convos.map((x,i)=><button key={x.id} onClick={()=>setCv(i)} className={`w-full text-left p-3 border-b border-line flex gap-3 ${cv===i?'bg-raise':'hover:bg-raise/50'}`}><Av n={x.who}/><div className="min-w-0 flex-1"><div className="flex justify-between"><span className="font-medium">{x.who}</span><span className="text-dim text-[12px]">{x.when}</span></div><p className="text-dim truncate">{x.last}</p><div className="mt-1.5"><Pill t={x.status==='Interested'?'ok':'n'}>{x.status}</Pill></div></div></button>)}</div>
<div className="rounded-lg border border-line bg-panel p-5 space-y-4"><div className="space-y-2">{c.msgs.map(([w,t],i)=><div key={i} className={`max-w-[80%] px-3 py-2 rounded-lg ${w==='me'?'ml-auto bg-accent/15':'bg-raise'}`}>{t}</div>)}</div>
<div className="rounded-md border border-accent/25 bg-accent/[0.05] p-3"><div className="flex items-center gap-1.5 text-accent text-[12px]"><Sparkles size={12}/>Agent interpretation</div><p className="mt-1">{c.read}</p><p className="text-dim mt-1.5 flex gap-1.5"><CornerDownRight size={14} className="mt-0.5 shrink-0"/>{c.next}</p></div>
{c.draft?<div><textarea defaultValue={c.draft} rows={4} className="w-full resize-none bg-bg border border-line rounded-md p-3 leading-relaxed"/><div className="flex justify-between mt-3"><Btn v="x">Reject</Btn><Btn v="p"><Check size={14}/>Approve & send</Btn></div></div>:<p className="text-dim">No reply drafted. The agent has nothing useful to add.</p>}</div></div></>}
if(page==='Activity')return <><Head t="Activity" s="Everything the agent and you have done, newest first."/><div className="max-w-2xl relative pl-5 border-l border-line space-y-5">{feed.map(([t,w,k],i)=><div key={i} className="relative"><span className={`absolute -left-[25px] top-1.5 size-2 rounded-full ${k==='you'?'bg-accent':k==='sent'?'bg-ok':'bg-dim'}`}/><div>{t}</div><div className="text-dim text-[12px]">{w}</div></div>)}</div></>
return <><Head t="Settings" s="Coming with the real agent."/><Empty t="Nothing to configure yet" s="Search topics, sources, and scan schedule will live here."/></>}
const Side=()=><aside className="hidden lg:flex w-60 shrink-0 flex-col border-r border-line bg-panel p-3 h-screen sticky top-0">
<div className="flex items-center gap-2 px-2 py-2 mb-4"><div className="size-6 rounded-md bg-accent grid place-items-center"><ArrowUpRight size={54} color="#0b0c10"/></div><span className="font-semibold">Nudge</span></div>
<nav className="space-y-0.5">{nav.map(([n,I])=><button key={n} onClick={()=>setPage(n)} className={`w-full flex items-center gap-2.5 h-8 px-2.5 rounded-md transition ${page===n?'bg-raise text-ink':'text-dim hover:text-ink hover:bg-raise/50'}`}><I size={15}/>{n}{n==='Approval Queue'&&q.length>0&&<span className="ml-auto font-mono text-[11px] text-accent">{q.length}</span>}</button>)}</nav>
<div className="mt-auto relative">{agent&&<AgentPanel onRun={runScan} running={running} live={live}/>}<button onClick={()=>setAgent(!agent)} className="w-full text-left rounded-md border border-line p-3 text-[12px] hover:bg-raise/50 transition"><div className="flex items-center gap-2 font-medium"><Dot on={live}/>{live?'Agent running':'Agent idle'}<span className="ml-auto text-dim font-normal">Details</span></div><div className="text-dim mt-1.5 flex gap-1.5"><Sparkles size={12} className="text-accent mt-0.5 shrink-0"/>{running?'Scanning for new leads…':live?agentInfo.recent[0]?.[0]:'Waiting for the next scan'}</div><div className="mt-2 h-1 rounded bg-raise overflow-hidden"><div className="h-full w-[27%] bg-accent/70"/></div><div className="text-dim mt-1.5">{`Last scan ${agentInfo.last} · ${agentInfo.next}`}</div></button></div></aside>
return <div className="flex min-h-screen"><Side/><div className="flex-1 min-w-0">
<header className="h-14 border-b border-line flex items-center gap-3 px-5 sticky top-0 bg-bg/80 backdrop-blur z-10"><div className="lg:hidden font-semibold">Outreach Agent</div><div className="relative flex-1 max-w-md"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-dim"/><input placeholder="Search leads, posts, conversations..." className="w-full h-8 pl-8 pr-10 rounded-md bg-panel border border-line placeholder:text-dim"/><kbd className="absolute right-2 top-1/2 -translate-y-1/2 font-mono text-[10px] text-dim border border-line rounded px-1">⌘K</kbd></div><div className="ml-auto flex items-center gap-3"><span className="hidden sm:flex items-center gap-1.5 text-dim text-[12px]"><Dot on={live}/>{live?'Running':'Idle'}</span><Bell size={16} className="text-dim"/><Av n="Mrigank" s={28}/></div></header>
<main className="p-5 lg:p-8 max-w-[1100px]">{body()}</main></div>
{lead&&<><div className="fixed inset-0 bg-black/50 z-20" onClick={()=>setOpen(null)}/><aside className="slide fixed right-0 top-0 bottom-0 w-[520px] max-w-full bg-panel border-l border-line z-30 overflow-y-auto p-6">
<div className="flex items-start gap-3"><Av n={lead.name} s={44}/><div className="flex-1"><h2 className="text-[18px] font-semibold">{lead.name}</h2><div className="text-dim">{lead.role?`${lead.role} at ${lead.co}`:lead.co}</div></div><button onClick={()=>setOpen(null)} className="text-dim hover:text-ink"><X size={18}/></button></div>
<div className="mt-5"><Why t="Why this lead" score={lead.score} ev={lead.ev} sig={lead.tags}/></div>{lead.via&&posts.find(p=>p.id===lead.via)&&<><h3 className="font-medium mt-6 mb-2">Found via {isGh(lead)?'GitHub issue':'post'}</h3><Src p={posts.find(p=>p.id===lead.via)!}/></>}
<h3 className="font-medium mt-6 mb-2">Agent analysis</h3><p className="text-dim leading-relaxed">{lead.why}</p>
{!isGh(lead)&&<><h3 className="font-medium mt-6 mb-2">Recent activity</h3><div className="border-l border-line pl-4 space-y-3"><div><div>Public post about intermittent CI failures</div><div className="text-dim text-[12px]">2 days ago</div></div><div><div>Commented on a pytest-dev issue about xdist ordering</div><div className="text-dim text-[12px]">6 days ago</div></div></div></>}
<h3 className="font-medium mt-6 mb-2">Recommended action: {lead.act}</h3>
{queue.find(x=>x.who===lead.name)&&q.find(x=>x.who===lead.name)?<Draft d={q.find(x=>x.who===lead.name)!} id={q.find(x=>x.who===lead.name)!.id}/>:<p className="text-dim">No draft waiting for this lead.</p>}<div className="flex gap-1.5 mt-6 pt-4 border-t border-line"><Btn v="x" onClick={()=>{hide('l'+lead.id,'Ignored',lead.name);setOpen(null)}}>Ignore</Btn><Btn v="x" onClick={()=>{hide('l'+lead.id,'Marked not relevant',lead.name);setOpen(null)}}>Not relevant</Btn></div></aside></>}
{toast&&<div className="fixed bottom-5 left-1/2 -translate-x-1/2 z-40 bg-raise border border-line rounded-lg px-4 py-2.5 shadow-xl flex gap-2 items-center"><Check size={14} className="text-ok"/>{toast}</div>}
</div>}